/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Sep 20 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit LED = P2^0;
sbit Button = P3^1;

void delay(int t);

void main(void)
 { 
   // Write your code here
   LED = 0;     // Output
   while (1)
   {
    if (Button==0)  //  Button is pressed , means ground is applied to it
   { 
	  LED = ~LED;
	  delay(500); 
   }
	 }
}
  void delay(int t)
 {
    int i,j;
    for (i=0; i<=t; i++)
    for (j=0;j<=122; j++);  
 }