/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Sep 20 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit D1 = P2^0;
sbit D2 = P2^1;
sbit D3 = P2^2;
sbit D4 = P2^3;

sbit K1 = P3^1;
sbit K2 = P3^0;
sbit K3 = P3^2;
sbit K4 = P3^3;

void delay(int t);

void main(void)
 { 
   // Write your Code here
   while (1)
   {
       if (K1==0)  //  Button is pressed , means ground is applied to it
       { 
	  D1 = ~D1;
	  delay(500);
      }
			 
			 if (K2==0)  //  Button is pressed , means ground is applied to it
       { 
	  D2 = ~D2;
	  delay(500);
      }
			 
			 if (K3==0)  //  Button is pressed , means ground is applied to it
       { 
	  D3 = ~D3;
	  delay(500);
      }
			 
			 if (K4==0)  //  Button is pressed , means ground is applied to it
       { 
	  D4 = ~D4;
	  delay(500);
      }
   }
}
  void delay(int t)
 {
    int i,j;
    for (i=0; i<=t; i++)
    for (j=0;j<=122; j++);  
 }