/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Sep 21 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit D1 = P2^0;

void timer0 () interrupt 1          // Using IE.1 which Timer Interrupt 0
{
	  D1 = ~D1;  
}

void main(void)
 { 
   // Write your Code here
    TMOD= 0x01;    // Using Timer 0 in Mode 1 which is 16 bits
    TH0 = 0xDB;    // Generate a 10ms 
    TL0 = 0xFF;
    TR0 = 1;
    while (TF0==0);
    TF0=0;
	  TR0=0;
  
    IE = 0x82;		// Using only Timer Interrupt 0

 }
