/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Jun 26 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void Tx (unsigned char x);
void delay (unsigned int t);

void main(void)
 { 
   unsigned char i;
   unsigned name[]="Hello World\n\r";
   // Write your code here
   TMOD = 0x20;
   TH1 = 0xFD;
   SCON = 0x50;
   TR1 = 1; 
	 while (1)
{
     for (i=0;i<=11;i++)
{
while(RI==0)
name[i]=SBUF;
RI=0;
}
}
 void Tx (unsigned char x)
 {
	 SBUF = x;
	 while (TI ==0);
     TI = 0;
 }
 void delay (unsigned int t)
 {
	 int i,j;
	 for (i=1; i<t; i++)
	 for (j=1 ; j<1000; j++);
 }