/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Sep 21 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit D1 = P2^0;
sbit D2 = P2^1;
sbit D3 = P2^2;
sbit D4 = P2^3;

sbit K1 = P3^1;
sbit K2 = P3^0;

void delay (int t);

void INTR1 () interrupt 2          // Using IE.2 which External Interrupt 1 , K4 is interrupted
{
	  D4 = ~D4;
	  delay(500);  
 }
void INTR0 () interrupt 0          // Using IE.0 which External Interrupt 0, K3 is interrupted
{
	  D3 = ~D3;
	  delay(500);  
}

void main(void)
 { 
   // Write your Code here
   IE = 0x85;		// Using only external Interrupt 1
    while (1)
   {
	  D1 = 0;   // Pull Down state, Always turn ON on 0
	  D2 = 0;		// Pull Down state, Always turn ON on 0
	  }
 
	}
 void delay(int t)
 {
    int i,j;
    for (i=0; i<=t; i++)
    for (j=0;j<=122; j++);  
 }